### ISSUE TITLE
How can I find out what prints out the "loading artist informatio…" blurb before content renders

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/mgs2016#19]
![unspecified](https://cloud.githubusercontent.com/assets/324987/12278687/65344882-b950-11e5-824f-eaa63cda12c6.png)

once everything else is finished I'd like to make it slightly more intentionally placed/designed....

**Comment by webmasterkai** [comment]
This is hopefully temporary.

**Comment by bjornmeansbear** [comment]
great. I'm just an annoying designer at heart who gets caught up with the small crap like that

**Comment by webmasterkai** [comment]
Since we are loading all information dynamically on every full page load there is a delay as the json file loads. The text is defined as a prop here: https://github.com/OOKB/mgs2016/blob/mockup/src/containers/App.js#L48

The component itself is https://github.com/OOKB/mgs2016/blob/mockup/src/components/Loading.js
